[[launchers.custom]]
id = "VLCMovies"
system = "Movie"
media_dirs = ["D:\\Videos\\Movies"]
file_exts = [".mp4", ".mkv", ".avi", ".mov", ".flv", ".webm"]
execute = "powershell -WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -Command Start-Process -FilePath 'C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe' -ArgumentList '--fullscreen', '--play-and-exit', '--no-video-title-show', '\"[[media_path]]\"'"
